name: Release new version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v2

      - name: 'Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: 'Sett opp bruker i git'
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Release with Gradle
        id: release
        run: |
          ./gradlew release -Prelease.useAutomaticVersion=true \
          -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
          -Prelease.newVersion=${{ env.NEXT_VERSION }}

      - name: 'Publiser release som maven-pakke'
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}