name: Release new version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v2

      - name: 'Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Generate versions
        uses: HardNorth/github-version-generate@v1.3.0
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: '(?<=version=).+'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Release with Gradle
        id: release
        run: |
          ./gradlew release -Prelease.useAutomaticVersion=true \
          -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
          -Prelease.newVersion=${{ env.NEXT_VERSION }}