name: Release new version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Java'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 'Sett opp bruker i git'
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 'Build'
        run: ./gradlew build --stacktrace

      - name: 'Publiser release som maven-pakke'
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Sett neste versjon'
        id: release
        run: ./gradlew release -Prelease.useAutomaticVersion=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
