name: Release new version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v5

      - name: 'Java'
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 'Sett opp bruker i git'
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 'Build'
        run: ./gradlew build --stacktrace

      - name: 'Publiser release som maven-pakke'
        run: ./gradlew publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Sett neste versjon'
        id: release
        run: ./gradlew release -Prelease.useAutomaticVersion=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Sett versjons-informasjon'
        run: |
          echo "VERSION=$(grep ^version= gradle.properties | cut -d= -f2)" >> $GITHUB_ENV
          echo "COMMIT=$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_ENV

      - name: 'Generate release info'
        run: |
          echo "Releaset ${{env.COMMIT}} som ${{ env.VERSION }}" > ../release_info.txt

      - name: 'Upload release info'
        uses: actions/upload-artifact@v4
        with:
          name: release-info
          path: release_info.txt
